import { type ToolDefinition } from '@/types/tools';

export const TOOLS: ToolDefinition[] = [
  // ═══════════════════════════════════════════
  // Category 1: Audio Analysis & Forensics
  // ═══════════════════════════════════════════
  {
    id: 'hires-verifier',
    name: 'Hi-Res Audio Verifier',
    shortName: 'Hi-Res Verifier',
    route: '/hires-verifier',
    category: 'analysis',
    engine: 'analysis',
    description: 'Verify if your audio file is truly high-resolution or an upsampled fake. Analyzes bit depth, frequency bandwidth, and spectral content.',
    metaDescription: 'Free hi-res audio verifier. Check if your FLAC or WAV is genuine high-resolution or upsampled. Browser-based, no upload required.',
    icon: 'ShieldCheck',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    analyses: ['bitDepth', 'bandwidth', 'lossyDetect', 'dynamicRange', 'verdict'],
    keywords: ['hi-res', 'high resolution', 'verify', 'fake', 'upsampled', '24-bit', 'FLAC'],
  },
  {
    id: 'spectrogram',
    name: 'Spectrogram Viewer',
    shortName: 'Spectrogram',
    route: '/spectrogram',
    category: 'analysis',
    engine: 'analysis',
    description: 'Visualize the frequency content of your audio over time with an interactive spectrogram. Zoom, pan, and customize colors.',
    metaDescription: 'Free online spectrogram viewer. Visualize audio frequency content in real-time. Supports WAV, FLAC, MP3, and more.',
    icon: 'BarChart3',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    analyses: ['spectrogram'],
    keywords: ['spectrogram', 'frequency', 'FFT', 'visualization', 'spectral'],
  },
  {
    id: 'lufs-meter',
    name: 'LUFS Loudness Meter',
    shortName: 'LUFS Meter',
    route: '/lufs-meter',
    category: 'analysis',
    engine: 'analysis',
    description: 'Measure loudness in LUFS (ITU-R BS.1770-4). Get integrated, short-term, and momentary readings with true peak and LRA.',
    metaDescription: 'Free LUFS loudness meter. Measure integrated, short-term LUFS, true peak, and LRA. Check Spotify, YouTube compliance.',
    icon: 'Volume2',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    analyses: ['lufs'],
    keywords: ['LUFS', 'loudness', 'BS.1770', 'true peak', 'LRA', 'Spotify', 'mastering'],
  },
  {
    id: 'dynamic-range',
    name: 'Dynamic Range Meter',
    shortName: 'DR Meter',
    route: '/dynamic-range',
    category: 'analysis',
    engine: 'analysis',
    description: 'Measure the dynamic range (DR) score of your audio. Detect over-compression, clipping, and loudness war casualties.',
    metaDescription: 'Free dynamic range meter. Measure DR score, crest factor, and detect clipping. Analyze the loudness war impact on your music.',
    icon: 'Activity',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    analyses: ['dynamicRange'],
    keywords: ['dynamic range', 'DR', 'crest factor', 'clipping', 'loudness war', 'compression'],
  },
  {
    id: 'waveform-viewer',
    name: 'Waveform Viewer',
    shortName: 'Waveform',
    route: '/waveform-viewer',
    category: 'analysis',
    engine: 'analysis',
    description: 'View your audio waveform with multi-resolution zoom. See peaks, RMS levels, and navigate through your audio visually.',
    metaDescription: 'Free online waveform viewer. Visualize audio waveforms with zoom and pan. Supports all major audio formats.',
    icon: 'AudioWaveform',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    analyses: ['waveform'],
    keywords: ['waveform', 'audio', 'viewer', 'peaks', 'RMS', 'visualization'],
  },
  {
    id: 'stereo-analyzer',
    name: 'Stereo Field Analyzer',
    shortName: 'Stereo Analyzer',
    route: '/stereo-analyzer',
    category: 'analysis',
    engine: 'analysis',
    description: 'Analyze stereo image with goniometer, correlation meter, and mid/side energy display. Check mono compatibility.',
    metaDescription: 'Free stereo field analyzer with goniometer and correlation meter. Check stereo width and mono compatibility.',
    icon: 'Disc3',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    analyses: ['stereo'],
    keywords: ['stereo', 'goniometer', 'correlation', 'mid-side', 'mono compatibility', 'stereo width'],
  },
  {
    id: 'file-inspector',
    name: 'Audio File Inspector',
    shortName: 'File Inspector',
    route: '/file-inspector',
    category: 'analysis',
    engine: 'analysis',
    description: 'Deep-inspect any audio file. View format details, metadata, tags, cover art, and technical specifications.',
    metaDescription: 'Free audio file inspector. View codec, bitrate, sample rate, metadata, ID3 tags, and cover art. No upload required.',
    icon: 'FileSearch',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a', 'wma', 'ape', 'wv'],
    keywords: ['file info', 'metadata', 'ID3', 'tags', 'inspector', 'codec', 'format'],
  },
  {
    id: 'lossy-detector',
    name: 'Lossy Transcode Detector',
    shortName: 'Lossy Detector',
    route: '/lossy-detector',
    category: 'analysis',
    engine: 'analysis',
    description: 'Detect if a lossless file was transcoded from a lossy source. Identifies spectral holes and encoder fingerprints.',
    metaDescription: 'Free lossy transcode detector. Detect if FLAC or WAV was converted from MP3 or AAC. Spectral analysis in browser.',
    icon: 'ScanSearch',
    acceptsFormats: ['wav', 'flac', 'aiff'],
    analyses: ['lossyDetect', 'bandwidth'],
    keywords: ['lossy', 'transcode', 'detect', 'fake lossless', 'spectral holes', 'MP3 to FLAC'],
  },
  {
    id: 'spectrum-analyzer',
    name: 'Spectrum Analyzer',
    shortName: 'Spectrum',
    route: '/spectrum-analyzer',
    category: 'analysis',
    engine: 'analysis',
    description: 'View the average frequency spectrum of your audio with 1/3 octave bands and A/C/Z weighting options.',
    metaDescription: 'Free online spectrum analyzer. View frequency spectrum with octave bands and weighting curves. Browser-based audio analysis.',
    icon: 'BarChart',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    analyses: ['spectrum'],
    keywords: ['spectrum', 'frequency', 'analyzer', 'octave', 'weighting', 'EQ'],
  },
  {
    id: 'audio-compare',
    name: 'Audio Comparator',
    shortName: 'Compare',
    route: '/audio-compare',
    category: 'analysis',
    engine: 'analysis',
    description: 'Compare two audio files side-by-side. View spectrograms, loudness, and quality metrics for both files.',
    metaDescription: 'Free audio file comparator. Compare two audio files side-by-side with spectrograms and quality metrics.',
    icon: 'Columns2',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    keywords: ['compare', 'A/B', 'side-by-side', 'difference', 'quality'],
  },
  {
    id: 'batch-analyzer',
    name: 'Batch Album Analyzer',
    shortName: 'Batch Analyzer',
    route: '/batch-analyzer',
    category: 'analysis',
    engine: 'analysis',
    description: 'Analyze an entire album at once. Get DR scores, loudness readings, and quality metrics for all tracks in a table.',
    metaDescription: 'Free batch audio analyzer. Analyze entire albums with DR scores and loudness metrics for every track.',
    icon: 'ListMusic',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    analyses: ['dynamicRange', 'lufs'],
    keywords: ['batch', 'album', 'analyzer', 'DR', 'loudness', 'table', 'multi-track'],
  },
  {
    id: 'freq-response',
    name: 'Frequency Response Plotter',
    shortName: 'Freq Response',
    route: '/freq-response',
    category: 'analysis',
    engine: 'analysis',
    description: 'Plot the frequency response curve of your audio. Useful for analyzing headphone and speaker measurements.',
    metaDescription: 'Free frequency response plotter. Plot and analyze frequency response curves for headphone and speaker measurements.',
    icon: 'TrendingUp',
    acceptsFormats: ['wav', 'flac', 'aiff'],
    analyses: ['spectrum'],
    keywords: ['frequency response', 'FR', 'headphone', 'speaker', 'measurement', 'curve'],
  },

  // ═══════════════════════════════════════════
  // Category 2: Audio Processing & Conversion
  // ═══════════════════════════════════════════
  {
    id: 'audio-converter',
    name: 'Audio Format Converter',
    shortName: 'Converter',
    route: '/audio-converter',
    category: 'processing',
    engine: 'ffmpeg',
    description: 'Convert audio files between formats. FLAC to MP3, WAV to AAC, and more. All processing in your browser.',
    metaDescription: 'Free online audio converter. Convert FLAC to MP3, WAV to AAC, and more. No upload — converts in your browser.',
    icon: 'RefreshCw',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    keywords: ['convert', 'FLAC to MP3', 'WAV to AAC', 'audio converter', 'format'],
  },
  {
    id: 'audio-trimmer',
    name: 'Audio Trimmer',
    shortName: 'Trimmer',
    route: '/audio-trimmer',
    category: 'processing',
    engine: 'ffmpeg',
    description: 'Trim audio files with a visual waveform editor. Set start and end points precisely with draggable handles.',
    metaDescription: 'Free online audio trimmer. Cut and trim audio files with a visual waveform editor. No upload required.',
    icon: 'Scissors',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    keywords: ['trim', 'cut', 'audio editor', 'waveform', 'start', 'end'],
  },
  {
    id: 'audio-normalizer',
    name: 'Audio Normalizer',
    shortName: 'Normalizer',
    route: '/audio-normalizer',
    category: 'processing',
    engine: 'ffmpeg',
    description: 'Normalize audio loudness to a target LUFS level. Perfect for podcast and music mastering preparation.',
    metaDescription: 'Free audio normalizer. Normalize loudness to target LUFS for Spotify, YouTube, or podcast standards.',
    icon: 'SlidersHorizontal',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    keywords: ['normalize', 'loudness', 'LUFS', 'gain', 'level', 'mastering'],
  },
  {
    id: 'waveform-image',
    name: 'Waveform Image Generator',
    shortName: 'Waveform Image',
    route: '/waveform-image',
    category: 'processing',
    engine: 'analysis',
    description: 'Generate beautiful waveform images from your audio files. Customize colors, size, and style. Download as PNG.',
    metaDescription: 'Free waveform image generator. Create beautiful audio waveform images. Customize and download as PNG.',
    icon: 'Image',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    analyses: ['waveform'],
    keywords: ['waveform', 'image', 'PNG', 'visualize', 'social media', 'share'],
  },
  {
    id: 'tag-editor',
    name: 'Audio Tag Viewer',
    shortName: 'Tag Viewer',
    route: '/tag-editor',
    category: 'processing',
    engine: 'analysis',
    description: 'View audio metadata tags including ID3, Vorbis Comments, and cover art directly in your browser.',
    metaDescription: 'Free audio tag viewer. View ID3 tags, Vorbis Comments, and cover art in your browser. No software needed.',
    icon: 'Tags',
    acceptsFormats: ['mp3', 'flac', 'ogg', 'm4a'],
    keywords: ['tags', 'ID3', 'metadata', 'viewer', 'cover art', 'Vorbis'],
  },
  {
    id: 'metadata-stripper',
    name: 'Metadata Stripper',
    shortName: 'Strip Metadata',
    route: '/metadata-stripper',
    category: 'processing',
    engine: 'ffmpeg',
    description: 'Remove all metadata and tags from audio files for privacy. Download a clean file with no personal information.',
    metaDescription: 'Free metadata stripper. Remove all tags and metadata from audio files for privacy. Browser-based processing.',
    icon: 'Eraser',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    keywords: ['metadata', 'strip', 'remove', 'privacy', 'clean', 'tags'],
  },
  {
    id: 'sample-rate-converter',
    name: 'Sample Rate Converter',
    shortName: 'Resample',
    route: '/sample-rate-converter',
    category: 'processing',
    engine: 'ffmpeg',
    description: 'Resample audio to a different sample rate. Convert between 44.1kHz, 48kHz, 96kHz, 192kHz, and more.',
    metaDescription: 'Free sample rate converter. Resample audio between 44.1kHz, 48kHz, 96kHz, 192kHz. Browser-based.',
    icon: 'ArrowUpDown',
    acceptsFormats: ['wav', 'flac', 'aiff'],
    keywords: ['sample rate', 'resample', '44.1kHz', '48kHz', '96kHz', '192kHz', 'SRC'],
  },
  {
    id: 'channel-ops',
    name: 'Channel Operations',
    shortName: 'Channels',
    route: '/channel-ops',
    category: 'processing',
    engine: 'ffmpeg',
    description: 'Extract left or right channel, convert stereo to mono, or combine mono files to stereo.',
    metaDescription: 'Free audio channel tool. Extract L/R channels, convert stereo to mono or mono to stereo. In-browser processing.',
    icon: 'Split',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg'],
    keywords: ['channel', 'stereo', 'mono', 'left', 'right', 'extract', 'merge'],
  },

  {
    id: 'audio-merger',
    name: 'Audio Merger',
    shortName: 'Merger',
    route: '/audio-merger',
    category: 'processing',
    engine: 'ffmpeg',
    description: 'Concatenate two or more audio files into a single file. Reorder tracks, choose output format, and download the merged result.',
    metaDescription: 'Free online audio merger. Join multiple audio files into one. Supports MP3, WAV, FLAC, and more. Browser-based, no upload.',
    icon: 'Combine',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    keywords: ['merge', 'join', 'concatenate', 'combine', 'audio merger', 'append'],
  },
  {
    id: 'audio-splitter',
    name: 'Audio Splitter',
    shortName: 'Splitter',
    route: '/audio-splitter',
    category: 'processing',
    engine: 'ffmpeg',
    description: 'Split an audio file into multiple segments at custom time points. Download individual segments or all at once.',
    metaDescription: 'Free online audio splitter. Split audio files into segments at custom time points. Browser-based, no upload required.',
    icon: 'Slice',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    keywords: ['split', 'divide', 'segment', 'cut', 'audio splitter', 'slice'],
  },

  // ═══════════════════════════════════════════
  // Category 3: Video Processing
  // ═══════════════════════════════════════════
  {
    id: 'video-to-mp3',
    name: 'Video to MP3 Extractor',
    shortName: 'Video → MP3',
    route: '/video-to-mp3',
    category: 'video',
    engine: 'ffmpeg',
    description: 'Extract the audio track from any video file and save it as MP3. Choose your quality settings.',
    metaDescription: 'Free video to MP3 converter. Extract audio from MP4, WebM, AVI videos as MP3. No upload — browser-based.',
    icon: 'Music',
    acceptsFormats: ['mp4', 'webm', 'avi', 'mkv', 'mov'],
    keywords: ['video to MP3', 'extract audio', 'MP4 to MP3', 'convert', 'rip audio'],
  },
  {
    id: 'video-trimmer',
    name: 'Video Trimmer',
    shortName: 'Video Trim',
    route: '/video-trimmer',
    category: 'video',
    engine: 'ffmpeg',
    description: 'Trim video files by setting start and end times. Fast copy-codec trimming with no re-encoding.',
    metaDescription: 'Free online video trimmer. Cut and trim video files in your browser. Fast copy-codec mode available.',
    icon: 'ScissorsLineDashed',
    acceptsFormats: ['mp4', 'webm', 'avi', 'mkv', 'mov'],
    keywords: ['video trim', 'cut video', 'video editor', 'start', 'end'],
  },
  {
    id: 'video-compressor',
    name: 'Video Compressor',
    shortName: 'Compress Video',
    route: '/video-compressor',
    category: 'video',
    engine: 'ffmpeg',
    description: 'Compress video files to reduce size. Control quality with CRF slider and see estimated file size.',
    metaDescription: 'Free video compressor. Reduce video file size with quality control. Browser-based, no upload.',
    icon: 'Minimize2',
    acceptsFormats: ['mp4', 'webm', 'avi', 'mkv', 'mov'],
    keywords: ['compress', 'video', 'reduce size', 'CRF', 'quality', 'smaller'],
  },
  {
    id: 'video-to-gif',
    name: 'Video to GIF Converter',
    shortName: 'Video → GIF',
    route: '/video-to-gif',
    category: 'video',
    engine: 'ffmpeg',
    description: 'Convert video clips to animated GIFs. Control FPS, width, and preview before downloading.',
    metaDescription: 'Free video to GIF converter. Create animated GIFs from video clips. Control FPS and size. Browser-based.',
    icon: 'FileImage',
    acceptsFormats: ['mp4', 'webm', 'avi', 'mkv', 'mov'],
    keywords: ['video to GIF', 'GIF maker', 'animated', 'convert', 'meme'],
  },
  {
    id: 'video-converter',
    name: 'Video Format Converter',
    shortName: 'Video Convert',
    route: '/video-converter',
    category: 'video',
    engine: 'ffmpeg',
    description: 'Convert videos between formats: MP4, WebM, AVI. Choose codec and quality settings.',
    metaDescription: 'Free video converter. Convert MP4 to WebM, AVI to MP4, and more. All processing in your browser.',
    icon: 'FileVideo',
    acceptsFormats: ['mp4', 'webm', 'avi', 'mkv', 'mov'],
    keywords: ['video converter', 'MP4', 'WebM', 'AVI', 'format', 'convert'],
  },
  {
    id: 'video-mute',
    name: 'Video Muter / Audio Replace',
    shortName: 'Mute Video',
    route: '/video-mute',
    category: 'video',
    engine: 'ffmpeg',
    description: 'Remove the audio track from a video file. Download a silent video or replace with new audio.',
    metaDescription: 'Free video muter. Remove audio from video files or replace the audio track. Browser-based tool.',
    icon: 'VolumeX',
    acceptsFormats: ['mp4', 'webm', 'avi', 'mkv', 'mov'],
    keywords: ['mute video', 'remove audio', 'silent video', 'replace audio', 'strip audio'],
  },
  {
    id: 'video-to-audio',
    name: 'Video to Audio Extractor',
    shortName: 'Video → Audio',
    route: '/video-to-audio',
    category: 'video',
    engine: 'ffmpeg',
    description: 'Extract the audio track from video in its original codec. No re-encoding for lossless extraction.',
    metaDescription: 'Free video to audio extractor. Extract audio in original codec without re-encoding. Browser-based.',
    icon: 'FileAudio',
    acceptsFormats: ['mp4', 'webm', 'avi', 'mkv', 'mov'],
    keywords: ['extract audio', 'video to audio', 'lossless', 'original codec', 'demux'],
  },
  {
    id: 'audio-to-video',
    name: 'Audio to Video Converter',
    shortName: 'Audio → Video',
    route: '/audio-to-video',
    category: 'processing',
    engine: 'ffmpeg',
    description: 'Convert an audio file into a YouTube-ready MP4 video with an optional background image. Choose resolution and aspect ratio.',
    metaDescription: 'Free audio to video converter. Create MP4 from audio with optional background image. Perfect for YouTube podcasts. Browser-based.',
    icon: 'Film',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    keywords: ['audio to video', 'podcast video', 'YouTube', 'MP4', 'static image', 'background'],
  },

  // ═══════════════════════════════════════════
  // Category 4: Signal Generators & Testing
  // ═══════════════════════════════════════════
  {
    id: 'tone-generator',
    name: 'Tone Generator',
    shortName: 'Tone Gen',
    route: '/tone-generator',
    category: 'generators',
    engine: 'oscillator',
    description: 'Generate precise audio tones. Choose frequency, waveform shape, and level. Play in real-time or download as WAV.',
    metaDescription: 'Free online tone generator. Generate sine, square, triangle, sawtooth tones at any frequency. Download as WAV.',
    icon: 'Sine' ,
    keywords: ['tone generator', 'sine wave', 'frequency', 'test tone', 'Hz', 'oscillator'],
  },
  {
    id: 'sweep-generator',
    name: 'Frequency Sweep Generator',
    shortName: 'Sweep Gen',
    route: '/sweep-generator',
    category: 'generators',
    engine: 'oscillator',
    description: 'Generate logarithmic or linear frequency sweeps. Test your speakers, headphones, and hearing range.',
    metaDescription: 'Free frequency sweep generator. Create log or linear sweeps to test speakers and headphones. Download as WAV.',
    icon: 'ArrowRight',
    keywords: ['sweep', 'frequency sweep', 'chirp', 'test', 'speaker', 'headphone'],
  },
  {
    id: 'noise-generator',
    name: 'Noise Generator',
    shortName: 'Noise Gen',
    route: '/noise-generator',
    category: 'generators',
    engine: 'oscillator',
    description: 'Generate white, pink, brown, blue, violet, and grey noise. Use for testing, relaxation, or sound masking.',
    metaDescription: 'Free noise generator. White, pink, brown, blue, violet, grey noise. Play in browser or download as WAV.',
    icon: 'Zap',
    keywords: ['noise', 'white noise', 'pink noise', 'brown noise', 'generator', 'ambient'],
  },
  {
    id: 'hearing-test',
    name: 'Online Hearing Test',
    shortName: 'Hearing Test',
    route: '/hearing-test',
    category: 'generators',
    engine: 'oscillator',
    description: 'Test your hearing with a frequency sweep audiometric test. See your hearing range on an audiogram chart.',
    metaDescription: 'Free online hearing test. Test your hearing range with audiometric frequency sweeps. View results on an audiogram.',
    icon: 'Ear',
    keywords: ['hearing test', 'audiogram', 'audiometry', 'frequency range', 'hearing loss'],
  },
  {
    id: 'dac-test',
    name: 'DAC & Headphone Test Suite',
    shortName: 'DAC Test',
    route: '/dac-test',
    category: 'generators',
    engine: 'oscillator',
    description: 'Test your DAC and headphones with channel checks, frequency response tests, and dynamic range tests.',
    metaDescription: 'Free DAC and headphone test suite. Channel check, frequency response, and dynamic range tests in your browser.',
    icon: 'Headphones',
    keywords: ['DAC test', 'headphone test', 'channel check', 'frequency response', 'audio test'],
  },

  // ═══════════════════════════════════════════
  // Category 5: Reference & Education
  // ═══════════════════════════════════════════
  {
    id: 'bitrate-calculator',
    name: 'Audio Bitrate Calculator',
    shortName: 'Bitrate Calc',
    route: '/bitrate-calculator',
    category: 'reference',
    engine: 'none',
    description: 'Calculate audio file sizes from format, bitrate, sample rate, bit depth, channels, and duration.',
    metaDescription: 'Free audio bitrate calculator. Calculate file size for WAV, FLAC, MP3, AAC. Plan storage and bandwidth.',
    icon: 'Calculator',
    keywords: ['bitrate', 'calculator', 'file size', 'storage', 'bandwidth', 'WAV size'],
  },
  {
    id: 'format-reference',
    name: 'Audio Format Reference Guide',
    shortName: 'Format Guide',
    route: '/format-reference',
    category: 'reference',
    engine: 'none',
    description: 'Compare audio formats side-by-side. FLAC vs WAV vs MP3 vs AAC vs OGG. Learn about codecs, quality, and use cases.',
    metaDescription: 'Audio format comparison guide. FLAC vs WAV vs MP3 vs AAC. Learn about codecs, quality, and when to use each format.',
    icon: 'BookOpen',
    keywords: ['format', 'comparison', 'FLAC vs WAV', 'MP3 vs AAC', 'codec', 'guide', 'reference'],
  },
  {
    id: 'bluetooth-codecs',
    name: 'Bluetooth Audio Codec Comparison',
    shortName: 'BT Codecs',
    route: '/bluetooth-codecs',
    category: 'reference',
    engine: 'none',
    description: 'Compare Bluetooth audio codecs: LDAC, aptX HD, aptX, AAC, SBC. Understand quality, latency, and compatibility.',
    metaDescription: 'Bluetooth codec comparison. LDAC vs aptX HD vs aptX vs AAC vs SBC. Quality, latency, and device compatibility guide.',
    icon: 'Bluetooth',
    keywords: ['Bluetooth', 'LDAC', 'aptX', 'AAC', 'SBC', 'codec', 'wireless', 'latency'],
  },
  {
    id: 'media-player',
    name: 'Media Player',
    shortName: 'Player',
    route: '/media-player',
    category: 'reference',
    engine: 'none',
    description: 'Play any audio or video file instantly in your browser. Drag, drop, and listen or watch — no processing needed.',
    metaDescription: 'Free online media player. Play WAV, FLAC, MP3, MP4, WebM, and more directly in your browser. No upload, no install.',
    icon: 'Play',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a', 'mp4', 'webm', 'avi', 'mkv', 'mov'],
    keywords: ['play', 'media player', 'audio player', 'video player', 'preview', 'listen', 'watch'],
  },

  // ═══════════════════════════════════════════
  // New Tools: Home Theater & Audiophile
  // ═══════════════════════════════════════════
  {
    id: 'speaker-test',
    name: 'Speaker Channel Test',
    shortName: 'Speaker Test',
    route: '/speaker-test',
    category: 'generators',
    engine: 'oscillator',
    description: 'Identify and test individual speaker channels in stereo, 5.1, or 7.1 surround. Includes polarity/phase check.',
    metaDescription: 'Free speaker channel test. Test stereo, 5.1, and 7.1 surround channels individually. Polarity check included. Browser-based.',
    icon: 'Speaker',
    keywords: ['speaker test', 'channel test', 'surround', '5.1', '7.1', 'left right', 'polarity'],
  },
  {
    id: 'subwoofer-test',
    name: 'Subwoofer & Bass Test',
    shortName: 'Sub Test',
    route: '/subwoofer-test',
    category: 'generators',
    engine: 'oscillator',
    description: 'Test your subwoofer with frequency steps, bass sweeps, and a crossover finder. Find room resonances and rolloff.',
    metaDescription: 'Free subwoofer test. Bass frequency steps 10-120Hz, sweep, crossover finder. Test room resonances. Browser-based.',
    icon: 'CircleDot',
    keywords: ['subwoofer', 'bass test', 'low frequency', 'crossover', 'room mode', 'LFE'],
  },
  {
    id: 'burn-in-generator',
    name: 'Headphone Burn-In Generator',
    shortName: 'Burn-In',
    route: '/burn-in-generator',
    category: 'generators',
    engine: 'oscillator',
    description: 'Run a timed headphone burn-in sequence with pink noise, sweeps, and dynamic content. Timer from 30 min to 24 hours.',
    metaDescription: 'Free headphone burn-in generator. Pink noise, frequency sweeps, and white noise cycles. Timer up to 24 hours.',
    icon: 'Flame',
    keywords: ['burn-in', 'headphone', 'break-in', 'pink noise', 'driver conditioning'],
  },
  {
    id: 'turntable-test',
    name: 'Turntable / Vinyl Test Tones',
    shortName: 'Turntable Test',
    route: '/turntable-test',
    category: 'generators',
    engine: 'oscillator',
    description: 'Generate test tones for turntable calibration: wow & flutter, anti-skating, speed accuracy, and channel balance.',
    metaDescription: 'Free turntable test tones. Wow & flutter, anti-skating bias, speed check for 33/45 RPM. Download as WAV.',
    icon: 'Disc',
    keywords: ['turntable', 'vinyl', 'wow flutter', 'anti-skating', 'speed', 'RPM', 'calibration'],
  },
  {
    id: 'surround-reference',
    name: 'Surround Sound Reference Guide',
    shortName: 'Surround Guide',
    route: '/surround-reference',
    category: 'reference',
    engine: 'none',
    description: 'Channel layouts for 2.0 to 7.1.4, speaker placement guidelines, crossover recommendations, and format comparisons.',
    metaDescription: 'Surround sound reference guide. Channel layouts, speaker placement, Dolby Atmos vs DTS:X comparison. Free guide.',
    icon: 'LayoutGrid',
    keywords: ['surround', '5.1', '7.1', 'Atmos', 'DTS', 'speaker placement', 'channel layout'],
  },
  {
    id: 'db-converter',
    name: 'dB Unit Converter',
    shortName: 'dB Converter',
    route: '/db-converter',
    category: 'reference',
    engine: 'none',
    description: 'Convert between dBFS, dBu, dBV, dBSPL, watts, and volts. Reference levels for gain staging.',
    metaDescription: 'Free dB unit converter. Convert dBFS, dBu, dBV, dBSPL, watts, volts. Gain staging reference calculator.',
    icon: 'ArrowLeftRight',
    keywords: ['dB', 'decibel', 'dBFS', 'dBu', 'dBV', 'dBSPL', 'gain staging', 'converter'],
  },
  {
    id: 'listening-monitor',
    name: 'Listening Fatigue Monitor',
    shortName: 'Listen Monitor',
    route: '/listening-monitor',
    category: 'reference',
    engine: 'none',
    description: 'Estimate safe listening time based on volume level. WHO/NIOSH guidelines with break reminders.',
    metaDescription: 'Free listening fatigue monitor. Estimate safe listening duration per WHO/NIOSH guidelines. Break reminders.',
    icon: 'Clock',
    keywords: ['listening fatigue', 'safe listening', 'SPL exposure', 'hearing health', 'WHO', 'NIOSH'],
  },
  {
    id: 'abx-test',
    name: 'ABX Blind Test',
    shortName: 'ABX Test',
    route: '/abx-test',
    category: 'analysis',
    engine: 'analysis',
    description: 'Double-blind ABX audio comparison. Load two files, guess which is X, and get statistical significance results.',
    metaDescription: 'Free ABX blind test. Compare two audio files with double-blind methodology. Statistical significance calculator.',
    icon: 'Shuffle',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    keywords: ['ABX', 'blind test', 'double blind', 'A/B', 'comparison', 'statistical'],
  },
  {
    id: 'clipping-detector',
    name: 'Clipping & True Peak Detector',
    shortName: 'Clip Detect',
    route: '/clipping-detector',
    category: 'analysis',
    engine: 'analysis',
    description: 'Scan for inter-sample peaks, hard clipping, and consecutive clipped samples with a visual waveform timeline.',
    metaDescription: 'Free clipping detector. Find inter-sample peaks and hard clipping in audio. Visual timeline of clip locations.',
    icon: 'TriangleAlert',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    keywords: ['clipping', 'true peak', 'ISP', 'inter-sample', 'distortion', 'overs'],
  },
  {
    id: 'room-analyzer',
    name: 'Room / Microphone Analyzer',
    shortName: 'Room Analyzer',
    route: '/room-analyzer',
    category: 'generators',
    engine: 'oscillator',
    description: 'Use your microphone to analyze room acoustics in real-time. Live frequency response, noise floor, and RT60 estimation.',
    metaDescription: 'Free room acoustics analyzer. Live frequency response with microphone. Noise floor and RT60 estimation.',
    icon: 'Mic',
    keywords: ['room acoustics', 'microphone', 'frequency response', 'noise floor', 'RT60', 'room mode'],
  },
  {
    id: 'ir-viewer',
    name: 'Impulse Response Viewer',
    shortName: 'IR Viewer',
    route: '/ir-viewer',
    category: 'analysis',
    engine: 'analysis',
    description: 'Visualize impulse response files: waveform, frequency response, RT60 decay, and waterfall spectrogram.',
    metaDescription: 'Free impulse response viewer. Visualize IR files with waveform, frequency response, and RT60 decay analysis.',
    icon: 'Zap',
    acceptsFormats: ['wav', 'flac', 'aiff'],
    keywords: ['impulse response', 'IR', 'convolution', 'RT60', 'reverb', 'room correction'],
  },
  {
    id: 'bit-perfect-test',
    name: 'Bit-Perfect Playback Test',
    shortName: 'Bit-Perfect',
    route: '/bit-perfect-test',
    category: 'generators',
    engine: 'oscillator',
    description: 'Generate a known PCM test signal to verify your playback chain applies no processing, SRC, or volume changes.',
    metaDescription: 'Free bit-perfect playback test. Verify no DSP, sample rate conversion, or volume adjustment in your audio chain.',
    icon: 'Binary',
    keywords: ['bit-perfect', 'WASAPI', 'exclusive mode', 'sample rate', 'DSP', 'transparency'],
  },

  // ═══════════════════════════════════════════
  // Headphone Tools
  // ═══════════════════════════════════════════
  {
    id: 'crossfeed',
    name: 'Crossfeed Simulator',
    shortName: 'Crossfeed',
    route: '/crossfeed',
    category: 'headphone',
    engine: 'oscillator',
    description: 'Simulate speaker-like listening on headphones by blending a filtered, delayed signal between channels.',
    metaDescription: 'Free crossfeed simulator for headphones. Reduce in-head localization with adjustable crossfeed. Browser-based.',
    icon: 'Headphones',
    acceptsFormats: ['wav', 'flac', 'aiff', 'mp3', 'ogg', 'aac', 'm4a'],
    keywords: ['crossfeed', 'headphone', 'speaker simulation', 'Meier', 'crosstalk', 'spatial'],
  },
  {
    id: 'binaural-beats',
    name: 'Binaural Beat Generator',
    shortName: 'Binaural Beats',
    route: '/binaural-beats',
    category: 'headphone',
    engine: 'oscillator',
    description: 'Generate binaural beats for focus, relaxation, or meditation. Adjustable base and beat frequency with session timer.',
    metaDescription: 'Free binaural beat generator. Delta, theta, alpha, beta, gamma frequencies. Session timer. Browser-based.',
    icon: 'Brain',
    keywords: ['binaural beats', 'brainwave', 'meditation', 'focus', 'alpha', 'theta', 'delta'],
  },
  {
    id: 'soundstage-test',
    name: 'Soundstage & Imaging Test',
    shortName: 'Soundstage',
    route: '/soundstage-test',
    category: 'headphone',
    engine: 'oscillator',
    description: 'Test headphone soundstage with panning sweeps, center image, width tests, and HRTF 3D positioning.',
    metaDescription: 'Free soundstage and imaging test for headphones. Panning, center image, HRTF 3D positioning. Browser-based.',
    icon: 'Compass',
    keywords: ['soundstage', 'imaging', 'panning', 'HRTF', '3D audio', 'spatial', 'headphone'],
  },
  {
    id: 'channel-balance',
    name: 'Channel Balance Test',
    shortName: 'Balance Test',
    route: '/channel-balance',
    category: 'headphone',
    engine: 'oscillator',
    description: 'Check headphone driver matching with alternating L/R tones at multiple frequencies. Detect imbalance in dB.',
    metaDescription: 'Free channel balance test for headphones. Check driver matching at multiple frequencies. Browser-based.',
    icon: 'Scale',
    keywords: ['channel balance', 'driver match', 'left right', 'imbalance', 'headphone test'],
  },
  {
    id: 'ear-training',
    name: 'EQ Ear Training',
    shortName: 'Ear Training',
    route: '/ear-training',
    category: 'headphone',
    engine: 'oscillator',
    description: 'Train your ears to identify EQ frequency bands. Gamified quiz with difficulty levels and score tracking.',
    metaDescription: 'Free EQ ear training tool. Learn to identify frequency bands by ear. Gamified with score tracking. Browser-based.',
    icon: 'Ear',
    keywords: ['ear training', 'EQ', 'frequency', 'mixing', 'critical listening', 'quiz'],
  },
  {
    id: 'headphone-guide',
    name: 'Headphone Comparison Guide',
    shortName: 'HP Guide',
    route: '/headphone-guide',
    category: 'headphone',
    engine: 'none',
    description: 'Reference guide for headphone types, impedance, amplification, target curves, and EQ tips.',
    metaDescription: 'Headphone comparison guide. Types, impedance, DAC/amp pairing, Harman target curves, and EQ tips. Free reference.',
    icon: 'BookOpen',
    keywords: ['headphone', 'guide', 'impedance', 'amplifier', 'Harman', 'target curve', 'EQ', 'planar'],
  },
];

export function getToolsByCategory(category: string): ToolDefinition[] {
  return TOOLS.filter(t => t.category === category);
}

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOLS.find(t => t.id === id);
}

export function getToolByRoute(route: string): ToolDefinition | undefined {
  return TOOLS.find(t => t.route === route);
}

export function searchTools(query: string): ToolDefinition[] {
  const q = query.toLowerCase();
  return TOOLS.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.shortName.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.keywords.some(k => k.toLowerCase().includes(q))
  );
}
